---
- name: Install Telnet and check SQL
  hosts: se1win.redelf.ch
    
  tasks:
  
- name: Install all updates and reboot as many times as needed
  win_updates:
    category_names: '*'
    reboot: yes
