
---
- hosts: all
  gather_facts: no
  tasks:
  - name: Return a failure back to Ansible
    ansible.windows.win_powershell:
      script: |
        if (Test-Path C:\bad.file) {
            $Ansible.Failed = $true
        }
       error: win_ps_out   
    
  - name: Conditional task for positive rc
    debug:
      msg: "PowerShell rc: {{ win_ps_out.rc }}"
    when: win_ps_out.rc <= 2147483647

  - name: Conditional task for negative rc
    debug:
      msg: "PowerShell rc: {{ win_ps_out.rc - 4294967296 }}"
    when: win_ps_out.rc > 2147483647

  - name: Install all security, critical and rollup updates without a scheduled task
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      - UpdateRollups
      - DefinitionUpdates
      log_path: C:\ansible-windows-update.txt
      state: installed
      reboot: yes
